### ISSUE TITLE
Uplink counter failure?

### ISSUE THREAD

**Issue by isabido** [dragino/LT-22222-L#2]
HI, I have tried this magnificent implementation to send some digital inputs to the other end.

I have noticed that with the default configuration with an SF12, the response time is somewhat slow (solved by going down to SF7), but the worst problem is that if the frame is lost or the remote equipment is turned off.

The transmitting LT continues sending the last packet, but it happens that if another new pulse enters again, It starts sending new packets without receiving them ad infinitum, and the only way to get it working again is to reset the device.

It is as if the counter became out of sync with the destination.

![image](https://github.com/dragino/LT-22222-L/assets/559650/3a375c34-af78-410f-b52f-885d4147668a)

![image](https://github.com/dragino/LT-22222-L/assets/559650/918ebbd9-8407-4d31-9192-0467b03cca14)

Thanks in advanced!

**Comment by engineer-lin** [comment]
Hi,sir.This is because the retransmission process is interrupted by an external interrupt, resulting in the failure to clear the send flag and resulting in continued packet sending. We've fixed this bug in v1.3.4.

**Comment by isabido** [comment]
Thanks for the quick response, fantastic support!
